services:
  nginx:
    image: nginx:alpine
    ports:
      - "${NGINX_HTTP_PORT:-80}:80"
      - "${NGINX_HTTPS_PORT:-443}:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./docker/nginx/cert:/etc/nginx/cert:ro
      - ./docker/nginx/pwd/.htpasswd:/etc/nginx/.htpasswd:ro
    environment:
      - TZ=Europe/Moscow
    networks:
      - common

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: api
    working_dir: /var/www/html
    ports:
      - "${PHP_PORT:-9000}:9000"
    volumes:
      - ./:/var/www/html
      - ./docker/php/conf/zz-custom.ini:/usr/local/etc/php/conf.d/zz-custom.ini
    networks:
      - common
    depends_on:
      - redis
      - nginx
    healthcheck:
      test: [ "CMD-SHELL", "php -v >/dev/null" ]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      TZ: Europe/Moscow
    labels:
      - co.elastic.logs/enabled=true

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    networks:
      - common
    environment:
      TZ: Europe/Moscow

  worker:
    profiles: [worker]
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: worker
    volumes:
      - ./:/var/www/html
    networks:
      - common
    restart: unless-stopped
    environment:
      TZ: Europe/Moscow
    labels:
      - co.elastic.logs/enabled=true
      - co.elastic.logs/json.keys_under_root=true
      - co.elastic.logs/json.add_error_key=true
      - co.elastic.logs/json.overwrite_keys=true

  websocket:
    profiles: [websocket]
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: websocket
    volumes:
      - ./:/var/www/html
    ports:
      - "${WS_PORT:-8080}:8080"
    depends_on:
      - redis
    networks:
      - common
    restart: unless-stopped
    labels:
      - co.elastic.logs/enabled=true
      - co.elastic.logs/json.keys_under_root=true
      - co.elastic.logs/json.add_error_key=true
      - co.elastic.logs/json.overwrite_keys=true

  cron:
    profiles: [cron]
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      target: scheduler
    volumes:
      - ./:/var/www/html
    depends_on:
      - redis
    networks:
      - common
    restart: unless-stopped
    working_dir: /var/www/html
    labels:
      - co.elastic.logs/enabled=true
      - co.elastic.logs/json.keys_under_root=true
      - co.elastic.logs/json.add_error_key=true
      - co.elastic.logs/json.overwrite_keys=true

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.15.3
    container_name: filebeat
    profiles: [filebeat]
    user: root
    command: ["-e", "-strict.perms=false", "-E", "logging.to_files=false"]
    environment:
      - TZ=Europe/Moscow
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - ELASTIC_USERNAME=${ELASTIC_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    networks:
      - common

  mysql:
    image: mysql:8
    platform: linux/amd64
    profiles: [database]
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: posiflora_test
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravelpassword
      TZ: Europe/Moscow
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - common

volumes:
  mysql:
  redis_data:

networks:
  common:
    name: ${DOCKER_NETWORK_NAME:-common}
    driver: bridge
